### ISSUE TITLE
Upload resources to S3

### ISSUE THREAD

**Issue by aiwilliams** [wfth/converter#1]
You'll need a UUID 😄

**Comment by isaacjwilliams** [comment]
Collector is already doing this in `download.rb`. See [159](https://github.com/wfth/collector/blob/master/download.rb#L159), [166](https://github.com/wfth/collector/blob/master/download.rb#L166), [191](https://github.com/wfth/collector/blob/master/download.rb#L191), and [194](https://github.com/wfth/collector/blob/master/download.rb#L194).

**Comment by aiwilliams** [comment]
The S3 upload must apply the public-read ACL to the objects it uploads.

**Comment by aiwilliams** [comment]
Oops, this should be on the collector.
